_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.5
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 64
data_csv:
    value: /home/bcv_researcher/merged_disk2/amp/Database/full_info_dataset.csv
dist_d_model:
    value: 256
dist_max_len:
    value: 224
dist_n_heads:
    value: 8
dist_n_layers:
    value: 4
epochs:
    value: 100
eval_interval:
    value: 10
fold:
    value: 1
gamma:
    value: 0.1
lr:
    value: 0.0001
maps_dir:
    value: /home/bcv_researcher/merged_disk2/amp/Matriz_Distancias/Distance_Maps
mode:
    value: cross_juanis
model_fold1:
    value: null
model_fold2:
    value: null
num_classes:
    value: 5
optimizer:
    value: adamw
project:
    value: AMP-Multimodal
run_name:
    value: cross_juanis_fold1_miniVit_gate_cross
scheduler:
    value: none
seed:
    value: 42
seq_d_model:
    value: 256
seq_max_len:
    value: 200
seq_n_heads:
    value: 8
seq_n_layers:
    value: 4
step_size:
    value: 10
wandb:
    value: true
weight_decay:
    value: 0.01
