_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 64
data_csv:
    value: /home/rvelasquez/NeurIPS_2025/Project_B/DataBase/Neurips/full_info_dataset.csv
dist_d_model:
    value: 256
dist_max_len:
    value: 224
dist_n_heads:
    value: 8
dist_n_layers:
    value: 4
epochs:
    value: 100
eval_interval:
    value: 10
fold:
    value: 1
gamma:
    value: 0.1
lr:
    value: 0.0001
maps_dir:
    value: /home/rvelasquez/NeurIPS_2025/Project_B/Matriz_Distancias/Distance_Maps
mode:
    value: cross_juanis
no_wandb:
    value: false
num_classes:
    value: 5
optimizer:
    value: adamw
project:
    value: AMP-Multimodal
run_name:
    value: cross_juanis_fold1
scheduler:
    value: none
seq_d_model:
    value: 256
seq_max_len:
    value: 200
seq_n_heads:
    value: 8
seq_n_layers:
    value: 4
step_size:
    value: 10
weight_decay:
    value: 0
